### ISSUE TITLE
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by Willham12** [react-native-maps/react-native-maps#4083]
Add this to fix the problem:
``
    implementation 'androidx.work:work-runtime-ktx:2.8.0-alpha01'
``

**Comment by Willham12** [comment]
https://github.com/react-native-maps/react-native-maps/blob/master/lib/android/build.gradle#L32

after that line i guess

**Comment by Lekhrajk** [comment]
> https://github.com/react-native-maps/react-native-maps/blob/master/lib/android/build.gradle#L32
> 
> after that line i guess
Thanks man
Finally, it worked in an emulator in dev mode before this it was not even opening the app. Hope will work in production also

**Comment by FadiAboMsalam** [comment]
@Willham12 thank u so much it worked <3

**Comment by Simon-TechForm** [comment]
Ref:  #4080

**Comment by falentinodjoka2801** [comment]
@Willham12  thank you so much brother, it works on Flutter too. I use Flutter for Android Development.

**Comment by gamestap99** [comment]
> Add this to fix the problem: `implementation 'androidx.work:work-runtime-ktx:2.8.0-alpha01'`

Thank for answer, It work on Flutter 2.10.3

**Comment by Simon-TechForm** [comment]
Fixed by #4116. Looking to publish a new release soon, in the mean time you can install from master.

**Comment by ahmedsawy1** [comment]
> 

in build.gradle module app

**Comment by theobouwman** [comment]
I am still facing this issue even on the latest release 1.3.2

**Comment by AlMamun-CSE** [comment]
> implementation 'androidx.work:work-runtime-ktx:2.8.0-alpha01'

not working me.
I am still facing this issue.

**Comment by sourabh-capri** [comment]
no working for me
