### ISSUE TITLE
Can't build version 0.31.0 on android

### ISSUE THREAD

**Issue by CVHOANG-coder** [react-native-maps/react-native-maps#4215]
I upgrade version from 0.30.1 to 0.31.0 and i can't build my app.  I use android sdk 31 and build on android 12 / realme gt neo 2
`
    "react": "17.0.2",
        "react-native": "0.66.3",    "react-native-maps": "^0.31.0", `

![image](https://user-images.githubusercontent.com/53090290/165722817-1a63315f-6c0d-42cb-a102-2552d6939505.png)

**Comment by midhungopipk** [comment]
did you able tp solve this issue?

**Comment by Simon-TechForm** [comment]
@CVHOANG-coder please have a look at the [installation docs](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#upgrading-to--v0310).

@midhungopipk I've just released a new version that should fix your issue. If not, please open a new issue with the bug you are experiencing.

**Comment by SohelIslamImran** [comment]
Facing runtime error https://github.com/react-native-maps/react-native-maps/issues/4235

**Comment by CVHOANG-coder** [comment]
![image](https://user-images.githubusercontent.com/55902338/168013096-b5128b0c-5cb7-40b1-a308-bd480b77a578.png)
@Simon-TechForm 
i updated to version 0.31.1 react-native-maps. But it's still not working.

**Comment by brokrete-oleksii** [comment]
For a new Google map renderer you have to use com.google.android.gms:play-services-maps:18.0.0 or higher. 
In this case try to change `playServicesVersion = '18.0.0'` in build.gradle. (or just remove line you have)

https://developers.google.com/maps/documentation/android-sdk/renderer
