### ISSUE TITLE
initialRegion does not work correctly on IOS

### ISSUE THREAD

**Issue by nes123** [react-native-maps/react-native-maps#4244]
# Bug report
  
After upgrading the last version of the package initialRegion does not work correctly on IOS, it does work on Android.

Works well in "react-native-maps": "^0.29.4".

## Environment info

      react-native: 0.67.0
      react: 17.0.2
      react-native-maps": ^0.30.1

    Target Platform: iOS

## Steps to reproduce

1. Open a page with a map

Describe what actually happens:
 
The map centers around the correct point but does not zoom to the correct delta

**Comment by longprao** [comment]
Confirmed this issue, the workaround that I'm using is using a `setTimeout` and change the region a little bit:

```
  useEffect(() => {
    setTimeout(() => {
      setRandom(generateRandomPoint({ latitude: position.latitude, longitude: position.longitude }, 50000))
      setShowCircle(true)
    }, 3000)
  }, [position])

<MapView
      provider={PROVIDER_GOOGLE}
      region={{
        ...random,
        latitudeDelta: 2,
        longitudeDelta: 2,
      }}
      style={styles.map}
    >
      {showCircle && (
        <Circle
          center={random}
          strokeColor={theme.transparency.blue25}
          strokeWidth={1}
          fillColor={theme.transparency.blue25}
          radius={100000}
        />
      )}
    </MapView>
  ```

The `<Circle>` component also does not take into account fill and stroke colors at the first render, that's why it also needs to be drawn on a timeout.

**Comment by longprao** [comment]
I'm using 0.31.1

**Comment by nes123** [comment]
Using region instead of initialregion is not a good solution as re-rendering takes you back to the state that was defined in "region"

**Comment by longprao** [comment]
initialRegion does not work with my method, because the map needs to be re-zoomed after the setTimeout.

**Comment by JestemTrzcinska** [comment]
The same problem here. However, in one component it works good, but on others it doesn't. The map is zoomed out. Didn't happend on 0.30.1, now on 0.31.0 is a problem.

**Comment by JestemTrzcinska** [comment]
Changed initialRegion to region works for me

**Comment by nialldbarber** [comment]
We are experiencing this issue as well on iOS. We went from `"0.27.1"` to `"0.31.1"`. 

The specific issues are: 

- `initialRegion` is reset to 0, 0 
- It's sometimes appears in a completely random region

Here are some of our relevant dependencies:
 "react-native": "0.65.2",

**Comment by Simon-TechForm** [comment]
Was able to reproduce this. Interestingly, the only thing that changed between 0.30.1 and 0.31.0 regarding this seems to be the Google Maps pod version (let me know if I missed something)?

I'm looking to release a beta version this weekend that includes my proposed fix for this. Stand by 👍

**Comment by nialldbarber** [comment]
@Simon-TechForm cheers for the quick response! It looks like updating to `0.30.2` solved the issue for us. I believe that uses Google Maps pod version `5.1.0`, so that might work for other people experiencing the same thing.

**Comment by Simon-TechForm** [comment]
As you might have guessed from the comment above, I've just published a beta release that should fix the issue. I would love to get feedback from anyone able to try it out 🤞

**Comment by maxgenest** [comment]
same for me, I tested beta and initialRegion is still not working properly.

**Comment by Simon-TechForm** [comment]
Interesting. Could you both elaborate on how you are testing the changes and what behaviour you are experiencing?

@tomasmozeris You posted a video where initialregion wasn't set until you interacted with the map, how is it behaving now?

I just ran the defaultmarker example and a triage project I have locally with the new version, and it's working as expected on my end 🤔

**Comment by maxgenest** [comment]
initialRegion does not work when I open the component the first time. But if I load the component another time it works perfectly. 

And sometimes it seems like I have a conflict with initialRegion and region when they are both set as props (the app close when the component load). But not everytime. 

Strange thing is I have no error message for both of those bugs.

**Comment by happyfloat** [comment]
Also tested the beta on ios with google maps and the initial region is not working most of the time.

**Comment by Guide4Ever** [comment]
Same issue occurring on my end. With `Map` and `Circle` component.

**Comment by tomasmozeris** [comment]
`initialRegion` works well on `iOS google maps` with `1.0.0-beta.7` 👍👍 appreciate your efforts

**Comment by happyfloat** [comment]
@Simon-TechForm works perfectly, thank you very much! It also seems to fix another bug for me on the ios simulator, where the map tiles are not aligned with the actual coordinates somehow...

**Comment by pot2mayo** [comment]
I tried version `1.1.0` and the `initial region` gets set correctly on iOS for half a second but then automatically zoom-out (without any state update from my side) to go back to the same state as in previous version when the bug occurred.
Any idea why the region would update itself automatically like that?
Thanks!

**Comment by tantabares** [comment]
I'm experiencing this issue with version 1.1.0: the first time my app is charged the map is all zoomed out. After a reload or a change in the coordinates, zoom is set as defined by initialRegion.

**Comment by tantabares** [comment]
> I tested beta today, issue with iOS with google maps and initialRegion is not working, can be reproduced with `/examples/DefaultMarker.js` I have no objective c / swift knowledge and I can't propose "real fix". If anyone searching for temporal workaround, you could try:
> 
> ```js
> const [loaded, setLoaded] = useState(false)
> const onRegionChangeComplete = (region) => { 
>   if (!loaded) { 
>     if (region.latitude != initialRegion.latitude || region.longitude != initialRegion.longitude) {
>       mapRef.animateToRegion(initialRegion, 1)
>     }
>     setLoaded(true)
>   } 
> }
> ```

this helped 100%, thank you

**Comment by princefishthrower** [comment]
This thread is absolutely incredible... such arcane changes to get things to 'work' on iOS

**Comment by Badra00** [comment]
Has this patch been removed from version 1.4.0-beta.1?

**Comment by polygbrl** [comment]
Just in case it's some of your situations, if you are passing a `ref` to your `MapView` like `ref={mapRef}`, initialRegion will not work on iOS (specifically, it is working on Android) because you override the internal reference. You have to assign the ref to yours like so `ref={map => mapRef = map]`. The difference in behavior between the both platforms may make it look like a bug with the package.

**Comment by Badra00** [comment]
> Just in case it's some of your situations, if you are passing a `ref` to your `MapView` like `ref={mapRef}`, initialRegion will not work on iOS (specifically, it is working on Android) because you override the internal reference. You have to assign the `ref` to yours like so `ref={map => mapRef = map}`. The difference in behavior between the both platforms may make it look like a bug with the package.

Even when doing like this: ref={(ref) => (mapRef.current = ref)}
I still have the issue, any idea @polygbrl ?

**Comment by polygbrl** [comment]
@haiderali3071 Issue was resolved one year ago and `react-natives-maps` is now at `1.7.1`. I would suggest that you actually read the thread and upgrade your package version.

> 🎉 This issue has been resolved in version 1.0.0-beta.1 🎉
> 
> The release is available on:
> 
> * [npm package (@beta dist-tag)](https://www.npmjs.com/package/react-native-maps/v/1.0.0-beta.1)
> * [GitHub release](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.0.0-beta.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

**Comment by Badra00** [comment]
> > Even when doing like this: ref={(ref) => (mapRef.current = ref)}
> 
> @Badra00 You are assigning a whole `ref` to your `ref.current`, that is incorrect in any case. Try `ref => mapRef = ref` as suggested. Did you also try without any ref at all?

How do you do this with hooks?

**Comment by polygbrl** [comment]
> > > Even when doing like this: ref={(ref) => (mapRef.current = ref)}
> > 
> > 
> > @Badra00 You are assigning a whole `ref` to your `ref.current`, that is incorrect in any case. Try `ref => mapRef = ref` as suggested. Did you also try without any ref at all?
> 
> How do you do this with hooks?

@Badra00 Your question is out of scope of this issue. Please ask React relative questions on Q/A platforms such as [stackoverflow.com](https://stackoverflow.com/) or try [the discussions of the `react-native-maps` project](https://github.com/react-native-maps/react-native-maps/discussions) if it is `react-native-maps` relative.

**Comment by aravi365** [comment]
facing the same issue on 1.8.0. Tested maps with static coordinates as initialRegion.

**Comment by jonathaneemmett** [comment]
Also seeing same issue on 1.8.3

**Comment by TierryBr** [comment]
I had this same problem happening on the IOS emulator, when running on the physical device the problem did not occur.

**Comment by kicaal** [comment]
same

**Comment by sbrighiu** [comment]
Just FYI, for anyone still having issues with this. I still have issues on iPhone 15 Pro Max, mostly on release builds.

As a reference, if maybe it's a different bug than this one, my map would load up on the phone and not zoom in where i set it with initialRegion. Sometimes it would move and zoom in, but if i pan it would instantly jump to a point on the map, slightly lower and to the right of the coordinates I set. From that point on whatever region I set or fit coordinates call would animate to a wrong point on the map, with no way of fixing it.

Using "react-native-maps": "1.18.0"

I recommend experimenting with the following:
1. If using react navigation bottom tabs, set the tab options lazy value to true (it would be nice if someone knows why this matters so much and can fix it)
2.  Read this article about refs and callback refs - the "skill issue" responses above for a simple 2 line explanation are annoying, primarily since all the examples available here use class components...
3. Add let mapRef: MapView | null = null; (I prefer the obvious null value until everything is ready) and ref={(ref)=>{if(ref) { mapRef = ref }}} bit to your code (and used it directly, without .current)
4. At this moment, you can try initialRegion again and see if everything is fixed for you
5. If it's not fixed, use isFocused from react-navigation + useEffect to trigger a region animation or a fitToCoordinates call, with no animation - in most cases this will be enough to pass the onMapReady and onMapLoaded (which is called multiple times)
6. You could try a setTimeout combined with onMapReady or with some other trigger like the result of the first onRegionChangeComplete, but i don't think its that much better than the isFocused trigger
7. If this still does not work, evaluate your memo()'s and see if you can remove them and test
8. In my case that is where the issue was finally fixed.

I hope it helps someone

**Comment by karuzo17** [comment]
@sbrighiu i am having this issue since now almost two weeks and its driving me crazy. Unfortunately your steps do not help me. For me initially everything is fine, the troubles start as soon as i logout the current demo user, and log back in again with a different user. The initialRegion seems to jumpt to Africa (even though the region is correctly set). Afterwards each animateToRegion is offset slightly to the lower right. Any idea what i could try in addition? I guess i have to create a new issue ...

**Comment by sbrighiu** [comment]
Conditionally render the map based on if you have a user or not. It's possible it may fix it, otherwise try to do some sort of loading on the map to delay the animation step a bit

Best regards,
Stefan

**Comment by sbrighiu** [comment]
The sad truth is it depends a lot... delaying the initial region animation by removing the initialRegion and doing it manually the first time when the screen in in focus is the first step. The only other advice i can give is to fix it somehow, then try to call it faster (relative to the mount of the component). If it breaks again, try calling it later and continue the search :) good luck :)
