### ISSUE TITLE
Maps are not working on development or production build

### ISSUE THREAD

**Issue by usmanct** [react-native-maps/react-native-maps#5141]
### Summary

App Map are working on expo testing build but On development build due to map view App is Crashed as I navigate to map screen but on expo local testing app is working fine. I am trying tp fix this issue by following this link and follow every step setup my google console for API configuration Link is { https://github.com/react-native-maps/react-native-maps/issues/2752#issuecomment-1996746029 } 

### Reproducible sample code

```TSX
import { StyleSheet, Text, View, Dimensions } from 'react-native';
import React, { useEffect, useState, useRef } from 'react';
import MapView, { Marker, Polyline , PROVIDER_GOOGLE } from 'react-native-maps';
import { getDistance } from 'geolib';
import * as Location from 'expo-location';
const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

const RunnerMap = ({
    totalDistance,
    setTotalDistance,
    mapRef, errorMsg,
    location,
    routeCoordinates,
    setErrorMsg,
    setRouteCoordinates,
    setLocation,
    speed,
    setSpeed
}: any) => {

    return (
        <View style={styles.container}>
            {errorMsg ? (
                <Text>{errorMsg}</Text>
            ) : (
                <MapView
                    ref={mapRef}
                    style={styles.map}
                    initialRegion={{
                        latitude: location?.coords?.latitude || 37.78825,
                        longitude: location?.coords?.longitude || -122.4324,
                        latitudeDelta: 0.01,
                        longitudeDelta: 0.01,
                    }}
                    showsUserLocation={true}
                    provider={PROVIDER_GOOGLE}
                >
                    <Marker coordinate={{
                        latitude: location?.coords?.latitude || 37.78825,
                        longitude: location?.coords?.longitude || -122.4324,
                    }} />
                    <Polyline
                        coordinates={routeCoordinates}
                        strokeColor="#000"
                        strokeWidth={6}
                    />
                </MapView>
            )}
            <View style={styles.distanceContainer}>
                <Text style={styles.distanceText}>
                    Distance Covered: {(totalDistance / 1000).toFixed(2)} km
                </Text>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        // backgroundColor:'yellow'
    },
    map: {
        width: screenWidth,
        height: screenHeight / 2 - 20,
    },
    distanceContainer: {
        padding: 10,
    },
    distanceText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
});

export default RunnerMap;
///// app.json code {
  "expo": {
    "name": "FootSteps-counter",
    "slug": "FootSteps-counter",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.usmanct.FootStepscounter",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "This app uses your location to track your steps.",
        "NSLocationAlwaysUsageDescription": "This app uses your location to track your steps even when the app is in the background.",
        "UIBackgroundModes": [
          "fetch"
        ]
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "permissions": [
        "ACTIVITY_RECOGNITION",
        "BACKGROUND_FETCH",
        "ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION",
        "ACCESS_BACKGROUND_LOCATION",
        "RECEIVE_BOOT_COMPLETED",
        "NOTIFICATIONS"
      ],
      "package": "com.usmanct.FootStepscounter",
      "versionCode": 1,
      "config":{
      "googleMaps":{
        "apiKey":"" Erase due to privacy
      }
    }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-dev-launcher",
        {
          "launchMode": "most-recent"
        }
      ],
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location."
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "" // Erase due to privacy
      }
    }
  }
}
```

### Steps to reproduce

Check the compatibility issue of this package with expo 51 

### Expected result

I expect that the map is also shown on the development build as show on the local expo build

### Actual result

![WhatsApp Image 2024-08-13 at 16 17 51 (1)](https://github.com/user-attachments/assets/adbbf6be-9213-4258-b9a3-46582af91f78)

### React Native Maps Version

1.17.3

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.3

### What version of Expo are you using?

SDK 48

### Device(s)

Redmi Note 8 pro

### Additional information

I am using the expo 51

**Comment by lucasjungdeveloper** [comment]
Same problem here

**Comment by lucasjungdeveloper** [comment]
I fixed it by adding
`<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_KEY" />`
To "android/app/src/main/AndroidManifest.xml"

**Comment by usmanct** [comment]
I have already add this in manifest file .. by the way on my end there is version compatibility issue which has been fixed

**Comment by Rokasbarasa1** [comment]
This is still an issue. I cannot get any version to work as this issue appears on every single solution attempt. The installation guide is outdated on this.
