### ISSUE TITLE
Marker are clipped on android

### ISSUE THREAD

**Issue by axelverglas** [react-native-maps/react-native-maps#5165]
### Summary

hello, 

I make custom markers on ios it's perfect but on android i have problem 
<img width="310" alt="Capture d’écran 2024-09-12 à 14 58 27" src="https://github.com/user-attachments/assets/ab662ffa-fbf4-4578-b269-4fa5606e6d0c">
markers are clipped
![Capture d’écran 2024-09-12 à 14 56 58](https://github.com/user-attachments/assets/0bea0831-ccaf-487e-87d6-139394610731)

### Reproducible sample code

```TSX
import { useEffect, useState, useRef, useCallback } from "react";
import MapView, { Marker } from "react-native-maps";
import * as Location from "expo-location";
import {
  YStack,
  Avatar,
  MarkerLocation2,
  CustomCard as Card,
  XStack,
  Text,
  CustomButton,
  MarkerLocation,
  View,
} from "@my/ui";
import { useCoach } from "app/utils/react-query/useCoach";
import { useRouter } from "solito/navigation";
import { User } from "app/schemas/user";
import { ChevronRight, LocateFixed, Send } from "@tamagui/lucide-icons";
import { Platform } from "react-native";

const parisRegion = {
  latitude: 48.8566,
  longitude: 2.3522,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
};

export const CoachLocationScreen = () => {
  const [selectedCoach, setSelectedCoach] = useState<User | null>(null);
  const [userLocation, setUserLocation] = useState<{
    latitude: number;
    longitude: number;
    latitudeDelta: number;
    longitudeDelta: number;
  } | null>(null);
  const mapRef = useRef<MapView>(null);
  const router = useRouter();
  const { coaches } = useCoach();

  const updateUserLocation = useCallback(
    (location: Location.LocationObject) => {
      const newUserLocation = {
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      };
      setUserLocation(newUserLocation);
    },
    []
  );

  useEffect(() => {
    (async () => {
      let { status } = await Location.requestForegroundPermissionsAsync();
      if (status === "granted") {
        try {
          let location = await Location.getCurrentPositionAsync({});
          const newUserLocation = {
            latitude: location.coords.latitude,
            longitude: location.coords.longitude,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          };
          updateUserLocation(location);
          mapRef.current?.animateToRegion(newUserLocation, 1000);

          // Watch position
          const watchId = await Location.watchPositionAsync(
            {
              accuracy: Location.Accuracy.High,
              timeInterval: 5000,
              distanceInterval: 10,
            },
            (location) => {
              updateUserLocation(location);
            }
          );

          return () => {
            watchId.remove();
          };
        } catch (error) {
          console.error(
            "Erreur lors de l'obtention de la localisation:",
            error
          );
          mapRef.current?.animateToRegion(parisRegion, 1000);
        }
      } else {
        console.log("Permission de localisation refusée");
        mapRef.current?.animateToRegion(parisRegion, 1000);
      }
    })();
  }, [updateUserLocation]);


  const navigateToCoachProfile = (coachId: string) => {
    router.push(`/profile/${coachId}`);
  };

  const handleMapPress = () => {
    setSelectedCoach(null);
  };

  const handleCoachSelect = (coach: User) => {
    setSelectedCoach(coach);
  };

  const mapPadding = Platform.select({
    ios: { bottom: 70, top: 0, left: 20, right: 0 },
    android: { bottom: 100, top: 20, left: 20, right: 20 },
    default: { bottom: 70, top: 0, left: 20, right: 0 },
  });

  return (
    <YStack f={1}>
      <MapView
        ref={mapRef}
        mapType="standard"
        pitchEnabled={true}
        rotateEnabled={true}
        zoomControlEnabled={false}
        showsCompass={false}
        style={{ flex: 1 }}
        mapPadding={mapPadding}
        initialRegion={parisRegion}
        onPress={handleMapPress}
      >
        {userLocation && (
          <Marker coordinate={userLocation}>
            <MarkerLocation />
          </Marker>
        )}
        {coachesWithLocation.map((coach, index) => {
          return (
            <Marker
              key={index}
              coordinate={coach.location}
              onPress={(e) => {
                e.stopPropagation();
                handleCoachSelect(coach);
              }}
            >
              <YStack
                ai="center"
                jc="center"
                zi={3}
                onPress={(e) => {
                  e.stopPropagation();
                  handleCoachSelect(coach);
                }}
              >
                <YStack
                  bc={selectedCoach?.id === coach.id ? "#E16D2A" : "white"}
                  p={4}
                  br="$4"
                  pos="absolute"
                  b="$5"
                >
                  <Avatar size="$5" br="$3">
                    <Avatar.Image src={coach.avatarUrl} />
                  </Avatar>
                </YStack>
                <MarkerLocation2 size={40} />
              </YStack>
            </Marker>
          );
        })}
      </MapView>
    </YStack>
  );
};
```

### Steps to reproduce

just go on maps

### Expected result

I would like the markers not to be cut

### Actual result

markers are clipped

### React Native Maps Version

1.15.2

### What platforms are you seeing the problem on?

Android

### React Native Version

0.74.2

### What version of Expo are you using?

SDK 48

### Device(s)

google pixel 6 pro

**Comment by DavidAmyot** [comment]
I believe I have the same issue. I use an svg icon and when set to a smaller size such as 48x48, it works fine but something like 96x96 it is clipped until I tap on it.

**Comment by axelverglas** [comment]
yes it’s big problem for android

**Comment by DavidAmyot** [comment]
@axelverglas 

For me, using the legacy renderer with `googleRenderer="LEGACY"` fixed multiple different bugs, including this one. A reload of the app did not work though, I had to completely close the app and start it back for the renderer change to take effect.

**Comment by C2thehris** [comment]
Maybe also checkout #5103? I had a bug where I was trying to use a custom element and it was getting clipped. That PR solved it

**Comment by axelverglas** [comment]
> Maybe also checkout #5103? I had a bug where I was trying to use a custom element and it was getting clipped. That PR solved it

I updated react native maps but my markers are still cut after maybe I'm doing something wrong

**Comment by DavidAmyot** [comment]
> > Maybe also checkout #5103? I had a bug where I was trying to use a custom element and it was getting clipped. That PR solved it
> 
> I updated react native maps but my markers are still cut after maybe I'm doing something wrong

Did you try using the legacy google renderer? Make sure to fully restart your application and clear the cache to be safe.

**Comment by C2thehris** [comment]
> > Maybe also checkout #5103? I had a bug where I was trying to use a custom element and it was getting clipped. That PR solved it
> 
> I updated react native maps but my markers are still cut after maybe I'm doing something wrong

The pull request hasn’t been merged yet, so you will need to create a patch manually.

**Comment by axelverglas** [comment]
> > > Peut-être aussi vérifier [le n° 5103](https://github.com/react-native-maps/react-native-maps/pull/5103) ? J'ai eu un bug où j'essayais d'utiliser un élément personnalisé et il était coupé. Ce PR a résolu le problème
> > 
> > 
> > J'ai mis à jour les cartes React Native mais mes marqueurs sont toujours coupés après peut-être que je fais quelque chose de mal
> 
> Avez-vous essayé d'utiliser l'ancien moteur de rendu Google ? Assurez-vous de redémarrer complètement votre application et de vider le cache pour plus de sécurité.

yes i try it but he didn't work

**Comment by axelverglas** [comment]
> > > Peut-être aussi vérifier [le n° 5103](https://github.com/react-native-maps/react-native-maps/pull/5103) ? J'ai eu un bug où j'essayais d'utiliser un élément personnalisé et il était coupé. Ce PR a résolu le problème
> > 
> > 
> > J'ai mis à jour les cartes React Native mais mes marqueurs sont toujours coupés après peut-être que je fais quelque chose de mal
> 
> La demande d'extraction n'a pas encore été fusionnée, vous devrez donc créer un correctif manuellement.

yes i did it but it's don't work but maybe it's my fault

**Comment by vuongdq2k** [comment]
Same +1

**Comment by DavidAmyot** [comment]
@salah-ghanim Any intention on looking into this? Upgrading to the latest expo sdk 52 which uses the new react-native architecture also triggers this, though this time even if I use the legacy google maps renderer.

**Comment by ayushh2k** [comment]
I have the same issue, custom marker and its callout are getting clipped in the new architecture

**Comment by dazza5000** [comment]
`googleRenderer="LEGACY" ` didn't work for me

**Comment by christian-lojack** [comment]
same problem I have     "react-native": "0.76.2" and  "react-native-maps": "^1.20.0", only happened in android , iOS without problem

**Comment by samclastine** [comment]
Same issue, unable to increase custom marker size beyond 38 units in react-native-maps—need a solution to remove this size constraint.

**Comment by ewikum** [comment]
Hey Folks, 

In your `android/gradle.properties`, chnage `newArchEnabled=false` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀

**Comment by DavidAmyot** [comment]
> Hey Folks,
> 
> In your `android/gradle.properties`, chnage `newArchEnabled=true` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀

The issue is that many of us don't want to disable the new architecture for all of its benefits just for google maps 🙂

**Comment by marcofuentes05** [comment]
> Hey Folks,
> 
> In your `android/gradle.properties`, chnage `newArchEnabled=true` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀

Disabling the new architecture is not a valid solution. The library should work with bouth the old and new arch

**Comment by lucaspieran** [comment]
> > Hey Folks,
> > In your `android/gradle.properties`, chnage `newArchEnabled=true` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀
> 
> Disabling the new architecture is not a valid solution. The library should work with bouth the old and new arch

Yes, I also agree, but it’s just for the meantime

**Comment by C2thehris** [comment]
Reacts Native Maps isn’t compatible with new architecture right now. See #5206

**Comment by ewikum** [comment]
> > > Hey Folks,
> > > In your `android/gradle.properties`, chnage `newArchEnabled=true` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀
> > 
> > 
> > Disabling the new architecture is not a valid solution. The library should work with bouth the old and new arch
> 
> Yes, I also agree, but it’s just for the meantime

Exactly, It depends on your needs, if the map is the big thing for your app, you have to trade it with the benefits of the new architecture for now. Just until they fix it.

**Comment by brownieboy** [comment]
> Hey Folks,
> 
> In your `android/gradle.properties`, chnage `newArchEnabled=true` to `newArchEnabled=false`. It will fix this for now. I tested on `0.76.3`. Thank me later ! 😀

That change initially crashed my app with errors like this:

>    ....(RootComponent), js engine: hermes
>  ERROR  Warning: Error: Exception in HostFunction: Malformed calls from JS: field sizes are different
 
Note the reference to "hermes" in the error.  Just below your setting, I noticed there was the setting `hermesEnabled=true`.  So I tried changing that to `hermesEnabled=false` and got lucky:  it fixed my errors, and my map markers are no longer truncated!

I'm not sure what the repercussions of turning off hermes are though.  It's for debugging, I think.

**Comment by Minerall06** [comment]
+1

**Comment by Gianfranco97** [comment]
Still relevant

**Comment by ppscvalentin** [comment]
I noticed the issue appears when using markers of different sizes. Hope that helps.

**Comment by suhascv7-nombolo** [comment]
Any updates on this?
This is blocking us from upgrading to the newArchitecture 
map is crucial part of our app

**Comment by hardikamber** [comment]
> Maybe also checkout [#5103](https://github.com/react-native-maps/react-native-maps/pull/5103)? I had a bug where I was trying to use a custom element and it was getting clipped. That PR solved it

This is working, can we get this merged we have create a patch for this

**Comment by dazza5000** [comment]
Are there any other alternative solutions? If not, can we merge this one?

**Comment by dazza5000** [comment]
This fix worked for me, but I couldn't get patch package to work correctly so I just copy/pasted to validate the fix

**Comment by rastropop** [comment]
Any progress about this fix?

**Comment by JJB1980** [comment]
Also having this issue, trying to render text and an icon

**Comment by anicache08** [comment]
Any news in this? I'm having same issue as well. It works fine in IOS but getting clipped in android.

**Comment by dennisc27** [comment]
Any progress with this issue? It works perfectly on IOS but will be clipped on android

**Comment by luisreiskeys** [comment]
🚀 I’ve just released a maintained alternative to react-native-map-clustering called react-native-map-supercluster.

It’s compatible with both iOS and Android, supports the New Architecture, and includes fixes for marker clipping on Android (useAndroidColorScale prop), plus customization options for clusters.

📦 Check it out:
https://github.com/luisreiskeys/react-native-map-supercluster

Feedback and contributions are welcome! 🙌

**Comment by ScreamZ** [comment]
@luisreiskeys You should check react-native-clusterer for clustring

**Comment by luisreiskeys** [comment]
> [@luisreiskeys](https://github.com/luisreiskeys) You should check react-native-clusterer for clustring

Tks, I'll check this

**Comment by aamaterasu91** [comment]
View under marker is still clipped off. Any solution plz

**Comment by irg1008** [comment]
> View under marker is still clipped off. Any solution plz

Update lo last version this is fixed now

**Comment by aamaterasu91** [comment]
Thank you, I updated to version 1.24.3 rn map and its not getting clipped now. But because im using expo sdk53 its complaining that im should use 1.20.x, hopefully no bug.

**Comment by awadeyar1** [comment]
I have fixed this issue by reducing the marker or cluster size to 34pt on Android Platform.
on iOS platform the larger clusters are allowed.
react-native-maps v1.23.8

**Comment by pinpong** [comment]
@axelverglas is the issue fixed? If so please close it.

**Comment by ashwinramdas12** [comment]
this is not fixed my markers are still cut off even with the latest react-native-maps package

**Comment by pinpong** [comment]
Try overflow: hidden

**Comment by ashwinramdas12** [comment]
overflow: hidden where? on the Marker component? or the rendered image within the Marker component?

**Comment by pinpong** [comment]
Wrap your Marker childs into a view and add style with overflow: hidden only

**Comment by ashwinramdas12** [comment]
<img width="319" height="337" alt="Image" src="https://github.com/user-attachments/assets/3583ff5f-2eba-4041-b672-86b4e475f48f" />

they are still cut off:

```if (imageSource) {
        return (
            <Marker
                key={post.id}
                onPress={onPress}
                coordinate={{
                    latitude: post.coordinates[1],
                    longitude: post.coordinates[0]
                }}
            >
                <View style={{
                    overflow: 'visible',
                }}>
                    {renderMarkerContent()}
                </View>
            </Marker>
        );
    }```

**Comment by samzmann** [comment]
I ran into this issue on:
- expo 53.0.20
- react-native-maps 1.20.1 (the official "Bundled version" in expo)
- new arch enabled

Updating to maps 1.24.13, and adding the `react-native-maps` plugin solved the issue.

**Comment by rpulkka** [comment]
> I ran into this issue on:
> 
>     * expo 53.0.20
> 
>     * react-native-maps 1.20.1 (the official "Bundled version" in expo)
> 
>     * new arch enabled
> 
> 
> Updating to maps 1.24.13, and adding the `react-native-maps` plugin solved the issue.

Updating react-native-maps to 1.24.13 seems to cause ` Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found.` at least when running react-native-testing-library tests https://github.com/react-native-maps/react-native-maps/issues/5655

**Comment by lucksp** [comment]
I am seeing this also on Android also since upgrading RNMaps version:

    "expo": "53.0.22",
    "react-native": "0.79.5",
    "react-native-maps": "1.20.1",

It seems when I have a custom marker, with height & width of `40`, on iOS there is no issue, but on Android, I have to scale down to max `36`

**Comment by AlejandroRM-DEV** [comment]
> I am seeing this also on Android also since upgrading RNMaps version:
> 
> ```
> "expo": "53.0.22",
> "react-native": "0.79.5",
> "react-native-maps": "1.20.1",
> ```
> 
> It seems when I have a custom marker, with height & width of `40`, on iOS there is no issue, but on Android, I have to scale down to max `36`

Did you have any luck?

**Comment by lucksp** [comment]
> Did you have any luck?

Luck with what?  I had to make a special case: Android is smaller than iOS

**Comment by sutgeorge** [comment]
@lucksp 

> I am seeing this also on Android also since upgrading RNMaps version:
> 
> ```
> "expo": "53.0.22",
> "react-native": "0.79.5",
> "react-native-maps": "1.20.1",
> ```
> 
> It seems when I have a custom marker, with height & width of `40`, on iOS there is no issue, but on Android, I have to scale down to max `36`

I have the exact same dependencies and the same problem on Android.

**Comment by sutgeorge** [comment]
@rpulkka 

> > I ran into this issue on:
> > ```
> > * expo 53.0.20
> > 
> > * react-native-maps 1.20.1 (the official "Bundled version" in expo)
> > 
> > * new arch enabled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Updating to maps 1.24.13, and adding the `react-native-maps` plugin solved the issue.
> 
> Updating react-native-maps to 1.24.13 seems to cause ` Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found.` at least when running react-native-testing-library tests [#5655](https://github.com/react-native-maps/react-native-maps/issues/5655)

Exactly 👍🏻

**Comment by Rk5422686** [comment]
If you prefer not to disable the new architecture or upgrade react-native-maps to the latest version, here’s a solution that worked for me.

My current setup in package.json:
```
    "react": "^18.3.1",
    "react-native": "^0.77.1",
    "react-native-maps": "^1.20.1",
```
I applied the following patch to fix the issue with custom markers being cut off:

```
diff --git a/android/src/main/java/com/rnmaps/maps/MapMarker.java b/android/src/main/java/com/rnmaps/maps/MapMarker.java
index b755f9b..a9f6442 100644
--- a/android/src/main/java/com/rnmaps/maps/MapMarker.java
+++ b/android/src/main/java/com/rnmaps/maps/MapMarker.java
@@ -448,6 +448,14 @@ public class MapMarker extends MapFeature {
     updateTracksViewChanges();
   }
 
+
+  @Override
+  protected void onLayout(boolean changed, int l, int t, int r, int b) {
+    super.onLayout(changed, l, t, r, b);
+    this.height = b-t;
+    this.width = r-l;
+  }
+
   private BitmapDescriptor getIcon() {
     if (hasCustomMarkerView) {
       // creating a bitmap from an arbitrary view
```
I've created a patch that you can apply directly— enjoy :)

**Comment by salah-ghanim** [comment]
closing this issue, latest releases of the library supports setting up subviews for android markers properly and take their size into consideration.

if the issue persists, please open a new one with reproducible example repository

**Comment by SanfetCoder** [comment]
> I ran into this issue on:
> 
> * expo 53.0.20
> * react-native-maps 1.20.1 (the official "Bundled version" in expo)
> * new arch enabled
> 
> Updating to maps 1.24.13, and adding the `react-native-maps` plugin solved the issue.

This worked for me!

**Comment by programmingwithsalim** [comment]
Has anyone faced this issue on 

- Expo 54.0.27
- react-native-maps 1.20.1

**Comment by MathiasVoie** [comment]
This issue is still relevant on Expo React-Native-Maps.

**Comment by Milwaukey** [comment]
Still have this problem with expo react-native-maps, that markers get cut.

**Comment by bendhiab-younes** [comment]
I have manually implemented this fix in my project "https://github.com/react-native-maps/react-native-maps/pull/5860/changes/7b7d63a42913961dcc0d6473ebcc627feda2b5bf#diff-77e98d1862e06a027310907fb50fd46c786bea7668549cf89189564559448b06R821"
here's a guide 


# Android Marker Clipping Hotfix 

This guide explains how anyone using `react-native-maps` can temporarily fix clipped custom markers on Android while PR [#5860](https://github.com/react-native-maps/react-native-maps/pull/5860) is awaiting release.

## 1. Context
- Google Maps' latest renderer caches marker bitmaps and fails to refresh when the underlying React Native view changes size (e.g., price bubbles).
- The upstream fix adds an `onLayout` override in `MapMarker.java` to detect size changes, clear the cached bitmap, and rerender.
- Until the fix ships, you can patch the library locally and keep it applied with `patch-package`.

## 2. Prerequisites
- Project already depends on `react-native-maps` (any React Native or Expo setup).
- For Expo-managed projects, run `npx expo prebuild` to generate the native Android directory so the Java sources exist.

## 3. Patch `MapMarker.java`
File path inside `node_modules`: `react-native-maps/android/src/main/java/com/rnmaps/maps/MapMarker.java`
Add/replace the `onLayout` method with:
```java
@Override
protected void onLayout(boolean changed, int l, int t, int r, int b) {
  super.onLayout(changed, l, t, r, b);

  int newWidth = r - l;
  int newHeight = b - t;
  if (newWidth > 0 && newHeight > 0 && (newWidth != this.width || newHeight != this.height)) {
    this.width = newWidth;
    this.height = newHeight;

    clearDrawableCache();
    if (marker != null) {
      update(true);
    }
  }
}
```
This mirrors the upstream PR logic: whenever layout size changes, invalidate the cached bitmap and refresh the marker icon.

## 4. Persist the change with `patch-package`
1. Install tooling:
   ```bash
   npm install --save-dev patch-package postinstall-postinstall
   ```
2. Add a `postinstall` hook so patches reapply after every install:
   ```json
   "scripts": {
     "postinstall": "patch-package"
   }
   ```
3. Generate the patch file:
   ```bash
   npx patch-package react-native-maps
   ```
   This creates `patches/react-native-maps+<version>.patch`. Commit it to your repo.

## 5. Rebuild Android
Rebuild or reinstall the app so the native code is compiled with the new behavior:
```bash
npx expo run:android   # or ./gradlew assembleDebug
```

## 6. Optional runtime fallback
While waiting for the official fix, you can force the legacy renderer when running on Android in case users still see clipping:
```tsx
<MapView
  googleRenderer={Platform.OS === 'android' ? 'LEGACY' : undefined}
  {...otherProps}
/>
```

## 7. Cleanup once upstream ships
- Upgrade to the `react-native-maps` version that includes PR #5860.
- Remove the patch file and the additional tooling/scripts if no longer needed.
- Switch back to the default renderer if you forced `LEGACY`.

By following these steps, you get unclipped custom markers immediately and can help confirm the upstream fix before it is released widely.
