### ISSUE TITLE
URL tile does not wotk

### ISSUE THREAD

**Issue by ademirtemur** [react-native-maps/react-native-maps#5310]
### Summary

I have a react-native app and using reactnative maps lib. I want to use openstreetmap's tiles in my project but does not display tiles while url tile.

### Reproducible sample code

```TSX
I have a react-native app, i want to use open-street-map, bot tiles des not display using URLTile. I tried --variant=release but did not  change anything. 

### Details
<MapView  style={StyleSheet.absoluteFill} mapType={MAP_TYPES.NONE} provider={undefined} zoomControlEnabled={true}
                >
                    <UrlTile
                        urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    />

                </MapView>

android:usesCleartextTraffic="true"
```

### Steps to reproduce

While app is running

### Expected result

Display on openstreetmap'tiles

### Actual result

<img width="339" alt="Screenshot 2024-12-28 at 14 48 39" src="https://github.com/user-attachments/assets/7d14f1a0-808d-4a46-a0be-b7a393a212d3" />

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.72.17

### What version of Expo are you using?

Not using Expo

### Device(s)

Android and IOS

**Comment by dpadula** [comment]
+1

**Comment by salah-ghanim** [comment]
@dpadula @ademirtemur this is one of the issues that were addressed while working on the alpha release / preparations for Fabric support.

please checkout the latest alpha version and test against it on iOS if it solves the issue.

**Comment by WahidN** [comment]
Any update on this? 

I am on version 1.20.1 and it's still not working

Expo: 51
Device: Android

It was working in previous version which was 1.10.0, but I dont think thats compatible with expo 51

**Comment by bsoufflet** [comment]
Any update on this? Which version should I use to fix this problem ?
Preferably an "Old Arch" version...
I am on expo 52.
Thanks

**Comment by bsoufflet** [comment]
> [@dpadula](https://github.com/dpadula) [@ademirtemur](https://github.com/ademirtemur) this is one of the issues that were addressed while working on the alpha release / preparations for Fabric support.
> 
> please checkout the latest alpha version and test against it on iOS if it solves the issue.

I tried the latest version 1.22.6 but it didn't worked...
I also tried 1.21 and 1.18 with no success...

**Comment by RobinGud** [comment]
react-native-maps version: 1.22.6
React Native version: 0.76.5 (new Arch)
Platform: Android 15
Not worked. 
Has anyone found a specific combination of versions or additional setup tweaks that make this feature render correctly?

**Comment by Mickael-van-der-Beek** [comment]
I consider this as still being an issue and it should probably be reopened.

**Comment by k-koehler** [comment]
im getting the same issue
