### ISSUE TITLE
React Native MapView crash application when dynamic sub view are added or removed rapidly

### ISSUE THREAD

**Issue by oferraanan** [react-native-maps/react-native-maps#5345]
### Summary

My Application "Air Map Israel" started failing in production on iOS
"expo": "~52.0.27",
"react-native": "0.76.6",
"react-native-maps": "1.18.0",

Failing on AIRMap.m method 
`  (void)insertReactSubview:(id<RCTComponent>)subview`
on last method line:
`    [_reactSubviews insertObject:(UIView *)subview atIndex:(NSUInteger) atIndex];`
**In some cases due to null subview and some cases the at index is grater than subviews size**
To fix it i wrapped it with a check
```TSX
    if (subview != nil) {
        NSUInteger safeIndex = MIN(atIndex, _reactSubviews.count);
        [_reactSubviews insertObject:(UIView *)subview atIndex:safeIndex];
    }
```
Did the same in method
`  (void)removeReactSubview:(id<RCTComponent>)subview`
```TSX
    if (subview != nil) {
        [_reactSubviews removeObject:(UIView *)subview];
    }
```
Need a fix for it.
Working fine on android

### Reproducible sample code

```TSX
// noinspection JSValidateTypes

import {View, Text, StyleSheet} from "react-native";
import MapView, {Marker} from "react-native-maps";
import {useEffect, useState} from "react";
import {Checkbox} from "expo-checkbox";

let isDebug = true;
let appTimerId = null;
let markersList = [];

export default function App() {

    const [addMarkers, setAddMarkers] = useState(true);
    const [markers, setMarkers] = useState([]);

    const [appTimerTime, setAppTimerTime] = useState(0)

    const startAppTimer = () => {
        if (appTimerId) clearInterval(appTimerId);
        appTimerId = setInterval(() => {
            setAppTimerTime((previousTime) => previousTime + 1);
        }, 1000);
    }

    const onMapReady = async () => {
        isDebug && console.log(new Date(), 'onMapReady');
        startAppTimer();
    };

    function addMarker() {
        markersList.push({
            title: 'Added ' + new Date().toLocaleTimeString(),
            coordinate: {
                latitude: 32.2 + appTimerTime / 10,
                longitude: 34.8 + appTimerTime / 10,
            }
        })
    }

    useEffect(() => {
        addMarker();
        setMarkers(markersList);
    }, [appTimerTime]);

    return (
        <View
            style={styles.header}
        >
            <MapView
                style={{
                    width: "100%",
                    height: "80%",
                }}
                showsUserLocation={true}
                onMapReady={onMapReady}
            >
                {addMarkers && markers?.length > 0 &&
                    markers.map((m, i) => {
                        return (
                            <Marker key={'marker_' + i}
                                    zIndex={99}
                                    coordinate={m.coordinate}
                                    anchor={{x: 0.5, y: 0.5}}
                                    title={m.title}
                            >
                            </Marker>
                        )
                    })
                }
            </MapView>
            <Text style={{
                padding: 10,
                fontWeight: 'bold',
                height: 50,
            }}>
                {'Show Markers'}
            </Text>
            <Checkbox
                value={addMarkers}
                onValueChange={(value) => setAddMarkers(value)}
                color={addMarkers ? 'blue' : undefined}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    header: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: 'oldlace'
    },
});
```

### Steps to reproduce

This demo Application adds markers to map view dynamically
There is a checkbox to enable and disable it

Play with the checkbox and see ios app crashes

### Expected result

Markers will be shown or removed from the map based on the checkbox

### Actual result

App crashes

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.76.6

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone 14 pro, iPhone 16 Pro simulator

**Comment by oferraanan** [comment]
You can find full project in github
https://github.com/oferraanan/map-issue

**Comment by oferraanan** [comment]
Android
![Image](https://github.com/user-attachments/assets/63beaddf-2510-417a-b46f-350559229d44)

iOS
![Image](https://github.com/user-attachments/assets/1626a183-773f-4ffd-843d-4b4e2f80336c)

**Comment by oferraanan** [comment]
This is the error stack on iOS (without the suggested fix)

[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be
nil'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b910c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180092da8 objc_exception_throw + 72
2   CoreFoundation                      0x000000018039ee9c -[__NSArrayM insertObject:atIndex:] + 1232
3   mapissue.debug.dylib                0x0000000106924058 -[AIRMap insertReactSubview:atIndex:] + 884
4   mapissue.debug.dylib                0x00000001064a0f88 -[RCTLegacyViewManagerInteropComponentView finalizeUpdates:] + 1312
5   mapissue.debug.dylib                0x00000001064b8e0c
_ZL27RCTPerformMountInstructionsRKNSt3__16vectorIN8facebook5react18ShadowViewMutationENS_9allocatorIS3_EEEEP24RCTComponentViewRegistryR41RCTMountingTransactionObserverCoordinatori
+ 2084
6   mapissue.debug.dylib                0x00000001064b85dc _ZZ41-[RCTMountingMan<…>

**Comment by meeran03share** [comment]
any update on this issue?

**Comment by oferraanan** [comment]
Hi
React native maps contributors
Please have a look into it - the crashes are going up

Until there will be a fix I released today a new version of my APP with the above suggested fix override (Xcode)

PS Expo recommended version is "1.18.0" I also tested with the latest "1.20.1" but problem is still there

Thanks

**Comment by KAMRONBEK** [comment]
Hi, I have same issue, any updates here?

**Comment by KAMRONBEK** [comment]
@oferraanan Hi, did you find solution?

**Comment by mustafasenturk** [comment]
@salah-ghanim could you look this issue? we need this.

**Comment by nikolovnikos** [comment]
same issue here, any fixes

**Comment by quentin23soleil** [comment]
Still happening with react-native-maps:1.20.1

**Comment by pelicanenglw** [comment]
I am seeing this issue as well - from Expo Go crash log:

0   CoreFoundation                	       0x1804b9100 __exceptionPreprocess + 160
1   libobjc.A.dylib               	       0x180092da8 objc_exception_throw + 72
2   CoreFoundation                	       0x18039eeac -[__NSArrayM insertObject:atIndex:] + 1232
3   Expo Go                       	       0x105667b78 -[AIRMap insertReactSubview:atIndex:] + 328

**Comment by quentin23soleil** [comment]
Anyone has a workaround working?

**Comment by edfungus** [comment]
I have the same problem but using the latest `1.23.8` seems to solve the issue. I'm on expo 53 as well

**Comment by masonlamy** [comment]
> Someone has a workaround working?

@quentin23soleil I went for a small patch to version 1.20.1:

[react-native-maps+1.20.1.patch](https://github.com/user-attachments/files/20679544/react-native-maps%2B1.20.1.patch)

**Comment by carlgrob5171989** [comment]
I am facing exactly same issue.
Is there any solution to fix it?

**Comment by carlgrob5171989** [comment]
> > Someone has a workaround working?
> 
> [@quentin23soleil](https://github.com/quentin23soleil) I went for a small patch to version 1.20.1:
> 
> [react-native-maps+1.20.1.patch](https://github.com/user-attachments/files/20679544/react-native-maps%2B1.20.1.patch)

The map does not crash
but it is missing ploygons.

**Comment by ASKIDAN** [comment]
in my case with DEFAULT_PROVIDER it was crashed with the same issue.
try to set provider in props. 
like 
```
 <MapView
      provider={PROVIDER_GOOGLE}
```

**Comment by nakapon9517** [comment]
I am suffering from the same problem. If it is improved in the latest version, you need to update the recommended version of expo

**Comment by nakapon9517** [comment]
The following patches were created and improvements were seen.
I will wait and see with this until the recommended version of expo goes up or expo54 comes along.

```
"expo": "~53.0.22",
"react-native": "0.79.5",
"react-native-maps": "1.20.1",
```

react-native-maps.patch
```
diff --git a/ios/AirGoogleMaps/AIRGoogleMap.m b/ios/AirGoogleMaps/AIRGoogleMap.m
index a1ffe694df8b5016dfffff75c454afde5bf32348..71ac56050429be0fbb03ec9f3e7c92b459f5adcb 100644
--- a/ios/AirGoogleMaps/AIRGoogleMap.m
+++ b/ios/AirGoogleMaps/AIRGoogleMap.m
@@ -188,7 +188,10 @@ - (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex
       [self insertReactSubview:(UIView *)childSubviews[i] atIndex:atIndex];
     }
   }
-  [_reactSubviews insertObject:(UIView *)subview atIndex:(NSUInteger) atIndex];
+  if (subview != nil) {
+      NSUInteger safeIndex = MIN(atIndex, _reactSubviews.count);
+      [_reactSubviews insertObject:(UIView *)subview atIndex:safeIndex];
+  }
 }
 #pragma clang diagnostic pop
 
diff --git a/ios/AirMaps/AIRMap.m b/ios/AirMaps/AIRMap.m
index 07a4638a5047ad7beb4859ae6341fb318d6ed522..e180ae9827f9273c16101e6f22376b70a957a51e 100644
--- a/ios/AirMaps/AIRMap.m
+++ b/ios/AirMaps/AIRMap.m
@@ -135,7 +135,10 @@ - (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex
             [self insertReactSubview:(UIView *)childSubviews[i] atIndex:atIndex];
         }
     }
-    [_reactSubviews insertObject:(UIView *)subview atIndex:(NSUInteger) atIndex];
+    if (subview != nil) {
+        NSUInteger safeIndex = MIN(atIndex, _reactSubviews.count);
+        [_reactSubviews insertObject:(UIView *)subview atIndex:safeIndex];
+    }
 }
 #pragma clang diagnostic pop
```

**Comment by salah-ghanim** [comment]
closing because it was solved in recent releases.

**Comment by Garett-MacGowan** [comment]
> closing because it was solved in recent releases.

Which release resolved this issue?

**Comment by kdvmgn** [comment]
I added a null check before inserting and removing the subview. Doesn't fix the root problem, but helps avoiding the crash. https://github.com/react-native-maps/react-native-maps/issues/3983#issuecomment-3602693924

**Comment by richstimson** [comment]
See potential root cause fix: https://github.com/react/react-native/issues/57872#issuecomment-5400175931
