### ISSUE TITLE
Unimplemented map components with Expo and PNPM monorepo

### ISSUE THREAD

**Issue by contactsimonwilson** [react-native-maps/react-native-maps#5437]
### Summary

The map components show the unimplemented component error instead of the map when building in a monorepo with a pnpm workspace.

### Reproducible sample code

```TSX
N/A
```

### Steps to reproduce

Build Expo project either locally or in EAS for a project in a pnpm workspace

### Expected result

Map displayed

### Actual result

Unimplemented component component is displayed

### React Native Maps Version

1.22.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.79.0

### What version of Expo are you using?

SDK 53

### Device(s)

iPhone XS

### Additional information

The development pod for react-native-maps shows under multiple nested folders in with the workspace configured.

![Image](https://github.com/user-attachments/assets/74f2eed3-2d48-4b51-8498-674933dafe89)

When the workspace config is removed and dependencies are in the same folder, the files show like this and the maps work as expected.

![Image](https://github.com/user-attachments/assets/bbd5664f-18b1-493a-a6be-59e83637fc29)

**Comment by salah-ghanim** [comment]
this should be fixed once https://github.com/react-native-maps/react-native-maps/pull/5441 is merged

**Comment by contactsimonwilson** [comment]
Thanks @salah-ghanim I look forward to testing it out.

**Comment by techied** [comment]
Hi, I just tested on react-native-maps 1.23.5 but it looks like this is still a problem

**Comment by kakajann** [comment]
Same here

**Comment by jarnove** [comment]
Same issue here, locally everything works, when building via CI, "Unimplemented component: <RNMapsGoogleMapView> is shown.

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/a16a8d34-8bfa-4c40-950a-9961dd7cdadd" />

**Comment by LukasMikolaj** [comment]
I got the same problem without monorepo using pnpm and setting `node-linker=hoisted` as pnpm [docs](https://pnpm.io/settings#nodelinker) suggest for React Native project fixed the issue.

**Comment by rafabulsing** [comment]
I'm seeing the same issue here.

I use npm rather than pnpm.

- React Native Maps Version: 1.23.8
- What platforms are you seeing the problem on: iOS (With both providers)
- React Native Version: 0.79.2
- What version of Expo are you using: SDK 53 (With new arch enabled)
- Device(s): iOS Simulator

With `PROVIDER_DEFAULT`, component renders as a red box with message: `Unimplemented component: <RNMapsMapView>`.

With `PROVIDER_GOOGLE`, I get the same box, with `Unimplemented component: <RNMapsGoogleMapView>`.

**Comment by xforcarlos** [comment]
> I'm seeing the same issue here.
> 
> I use npm rather than pnpm.
> 
> * React Native Maps Version: 1.23.8
> * What platforms are you seeing the problem on: iOS (With both providers)
> * React Native Version: 0.79.2
> * What version of Expo are you using: SDK 53 (With new arch enabled)
> * Device(s): iOS Simulator
> 
> With `PROVIDER_DEFAULT`, component renders as a red box with message: `Unimplemented component: <RNMapsMapView>`.
> 
> With `PROVIDER_GOOGLE`, I get the same box, with `Unimplemented component: <RNMapsGoogleMapView>`.

same with me

**Comment by anasnaeem23** [comment]
> I'm seeing the same issue here.
> 
> I use npm rather than pnpm.
> 
> * React Native Maps Version: 1.23.8
> * What platforms are you seeing the problem on: iOS (With both providers)
> * React Native Version: 0.79.2
> * What version of Expo are you using: SDK 53 (With new arch enabled)
> * Device(s): iOS Simulator
> 
> With `PROVIDER_DEFAULT`, component renders as a red box with message: `Unimplemented component: <RNMapsMapView>`.
> 
> With `PROVIDER_GOOGLE`, I get the same box, with `Unimplemented component: <RNMapsGoogleMapView>`.



> I'm seeing the same issue here.
> 
> I use npm rather than pnpm.
> 
> * React Native Maps Version: 1.23.8
> * What platforms are you seeing the problem on: iOS (With both providers)
> * React Native Version: 0.79.2
> * What version of Expo are you using: SDK 53 (With new arch enabled)
> * Device(s): iOS Simulator
> 
> With `PROVIDER_DEFAULT`, component renders as a red box with message: `Unimplemented component: <RNMapsMapView>`.
> 
> With `PROVIDER_GOOGLE`, I get the same box, with `Unimplemented component: <RNMapsGoogleMapView>`.

hey I am also facing the same issue did you find a workaround?

**Comment by rafabulsing** [comment]
@anasnaeem23 Not yet, unfortunately. I have some other stuff to ship before this becomes critical so I haven't tried troubleshooting it further then what I commented before. For now I'm just waiting/hoping for a fix.

**Comment by bigcupcoffee** [comment]
This was fixed in react-native `0.79.3` https://github.com/facebook/react-native/commit/ed7b4d86ab2b77b4cba6c2105e35047ac68c93e1 (@salah-ghanim 🎉)

For those that cannot update (I know react-native-linear-gradient acts weird on 0.79.3) you can still use my workaround

> As a temporary workaround we just copy `react-native-maps` folder into `node_modules` so it's not a symlink (tried also manually linking the package to `node_modules/.pnpm/...`, no luck). Just running this on post install:
> 
> #!/bin/bash
> 
> set -e
> 
> RN_MAPS_DIR=$(dirname "$(node -p "require.resolve('react-native-maps/package.json')")")
> TARGET_DIR="node_modules/react-native-maps"
> 
> rm -rf "$TARGET_DIR"
> mkdir -p "$(dirname "$TARGET_DIR")"
> cp -R "$RN_MAPS_DIR" "$TARGET_DIR"

**Comment by luan-nvg** [comment]
> O mesmo problema aqui, localmente tudo funciona, mas ao compilar via CI, "Componente não implementado: é exibido. (versão 1.23.8)
> 
> <img alt="Imagem" width="300" src="https://private-user-images.githubusercontent.com/1588620/445027281-a16a8d34-8bfa-4c40-950a-9961dd7cdadd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkzNDA0NTYsIm5iZiI6MTc0OTM0MDE1NiwicGF0aCI6Ii8xNTg4NjIwLzQ0NTAyNzI4MS1hMTZhOGQzNC04YmZhLTRjNDAtOTUwYS05OTYxZGQ3Y2RhZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MDdUMjM0OTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYxZThjNWM3NjA4ZDE2N2ZhZTY1MzE4ZTY4NDNhZWUxZTViYjIxOTcxNDQyNmI1ZTI0YWY1ZmM1MjdjZjExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KZ4IRCDABJttYXhj_Fpg6Bbe951tQoK-TFFEWPZd3Js">

     problem in  "react-native": "0.79.2",
    "react-native-maps": "1.23.10",

**Comment by Deepakict** [comment]
problem in  "react-native": "0.80.0",
"react-native-maps": "1.24.3",

**Comment by loekTheDreamer** [comment]
> problem in "react-native": "0.80.0", "react-native-maps": "1.24.3",

not just a monorepo issue https://github.com/react-native-maps/react-native-maps/issues/5585

**Comment by SOHAM068** [comment]
> Same issue here, locally everything works, when building via CI, "Unimplemented component: is shown. (version 1.23.8)
> 
> <img alt="Image" width="300" src="https://private-user-images.githubusercontent.com/1588620/445027281-a16a8d34-8bfa-4c40-950a-9961dd7cdadd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTEzNDU3MjIsIm5iZiI6MTc1MTM0NTQyMiwicGF0aCI6Ii8xNTg4NjIwLzQ0NTAyNzI4MS1hMTZhOGQzNC04YmZhLTRjNDAtOTUwYS05OTYxZGQ3Y2RhZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDFUMDQ1MDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNlYzMzMDlkNjMyZWNiMjczZTg3YWZlZTE1N2M3ZjhiNmM0YzhhMmJjZWQyNTk4YTUwYzBiZjFmYmMyNzdjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BKKCsmd_VqgmlxSCSMvUxpR3rJ3K5xLnqDq3tsrkQ0k">

Did you find any solution to this? Same issue here.

**Comment by eldawwy** [comment]
@contactsimonwilson 
@salah-ghanim  you can close this now it's working fine on 1.24.7
