### ISSUE TITLE
TS2344 When compiling with TypeScript 5.8.3 – React.ElementRef<React.ComponentType>

### ISSUE THREAD

**Issue by Raymond-47** [react-native-maps/react-native-maps#5464]
#### Environment

| Library               | Version          |
| --------------------- | ---------------- |
| **react-native-maps** | `1.22.6` (latest) |
| **react-native**      | `0.79.1`         |
| **react**             | `19.0.0`         |
| **typescript**        | `5.8.3`          |

---

#### 🐞 Current Behavior

When compiling with TypeScript 5.8.3, the following error is thrown:

```
node_modules/react-native-maps/lib/src/specs/NativeComponentMapView.ts:1080:31
TS2344: Type 'ComponentType<{}>' does not satisfy the constraint
'ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) |
 ((props: any) => ReactNode) | keyof IntrinsicElements'.

1080     viewRef: React.ElementRef<React.ComponentType>,
                                          ~~~~~~~~~~~~~
```

The same issue appears in other spec files as well, causing the TypeScript build to fail.

---

#### Suggested Fix

Using `React.ComponentRef` to replace `React.ElementRef`. `React.ElementRef` is deprecated in `"@types/react": "^19.1.2"`.

---

### Reproducible sample code

```TSX
yarn add -D typescript@5.8.3
npx tsc --noEmit
```

### Steps to reproduce

yarn add -D typescript@5.8.3
npx tsc --noEmit

### Expected result

Type-checking should succeed without errors on TypeScript 5.8+.

### Actual result

```
node_modules/react-native-maps/lib/src/specs/NativeComponentMapView.ts:1080:31
TS2344: Type 'ComponentType<{}>' does not satisfy the constraint
'ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) |
 ((props: any) => ReactNode) | keyof IntrinsicElements'.

1080     viewRef: React.ElementRef<React.ComponentType>,
                                          ~~~~~~~~~~~~~
```

### React Native Maps Version

1.22.6

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.79.1

### What version of Expo are you using?

Not using Expo

### Device(s)

-

### Additional information

The dependency versions in your monorepo are not consistent with those declared in the lib package. Such as `@types/react`, `@react-native/babel-preset`.

**Comment by salah-ghanim** [comment]
@Raymond-47 this should be solved with the latest release it included: 
  [5473](https://github.com/react-native-maps/react-native-maps/pull/5473 )
 [5472]( https://github.com/react-native-maps/react-native-maps/pull/5472)

**Comment by Raymond-47** [comment]
You closed the issue, but our problem remains unresolved. In fact, the TypeScript check failures stem from the latest TypeScript version, which introduces stricter type checks. As a result, we’re unable to pass `tsc --noEmit`. Would it be possible for you to upgrade the TypeScript version used in this library? Thank you!

**Comment by christiantakle** [comment]
@Raymond-47 Any reason you closed #5487? I was about to do the same work since we have the same issue and don't want to duplicate work or step on any toes.

Using local path for now

**Comment by Raymond-47** [comment]
@christiantakle another issue do the same thing and maybe the problem is resolved. https://github.com/react-native-maps/react-native-maps/issues/5492
