### ISSUE TITLE
This package is becoming unusable on Android, markers flicker or are cut off and TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” error

### ISSUE THREAD

**Issue by ashwinramdas12** [react-native-maps/react-native-maps#5655]
### Summary

The markers for this package are broken on Android. Not only is the flickering problem persistent, but the markers are also cut off on certain Android devices:

<img width="319" height="337" alt="Image" src="https://github.com/user-attachments/assets/e3df74d6-f21f-4f7a-95be-f789c35d07a8" />

I tried updating my package to 1.24.2 and added the necessary entries to app.json plugins array, and then I get hit with the "TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found”" error. I have to revert back to version 1.20.1 for my app to even function and the flickering and cut off markers persist.

I've tried the 1.24.X versions on expo go and with development builds and I get the same RNMapsAorModule not found error.

### Reproducible sample code

```TSX
<MapView
                        ref={mapRef}
                        className="w-full h-full"
                        customMapStyle={customMapStyle || defaultMapStyle}
                        onRegionChangeComplete={onRegionChangeComplete}
                        onLongPress={(event) => {
                            const { coordinate } = event.nativeEvent;
                            setLongPressCoordinates({
                                lat: coordinate.latitude,
                                lng: coordinate.longitude
                            });
                        }}
                        region={{
                            latitude: mapCoordinates.lat,
                            longitude: mapCoordinates.lng,
                            ...deltas,
                        }}
                        tracksViewChanges = {false}
                    >   
<Marker
                                            key={`cluster-${index}`}
                                            coordinate={{
                                                latitude: post.coordinates[1],
                                                longitude: post.coordinates[0],
                                            }}
                                        >
                                            <Image source={require('@/assets/images/adaptive-icon-new.png')} style={{width: 36, height: 36}}/>
                                        </Marker>
</MapView>
```

### Steps to reproduce

Use any custom image within the Marker component and it clips. And I am using a much more complex than this but even this doesnt work.

### Expected result

the full marker should show

### Actual result

the markers are clipped

### React Native Maps Version

1.20.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.79.4

### What version of Expo are you using?

SDK 53

### Device(s)

Pixel 3, Pixel 7 Pro

**Comment by SteveKibs** [comment]
I am getting the same error

**Comment by Byrby** [comment]
Hi!
Are you using `expo start` or `expo run:android` ?

It looks like `expo start` isn't working due to a native package reference.

**Comment by AI-Agent-01** [comment]
Same issues

**Comment by LeunensMichiel** [comment]
Yup, cut off markers here too. Marker is a simple react view that can have an expanded/collapsed state.

Noticed when upgrading our app from Expo 52 old arch => Expo 53 new arch

**Comment by androbro** [comment]
also having this issue. i would respectfully ask the collaborators to stop closing these tickets and actually look into this.
seen this error a few times and it always gets closed off without actually providing a clear fix. downgrading to 1.20.1 isnt really a solution.

**Comment by scd8418** [comment]
Same issue.

**Comment by laicai168-forreal** [comment]
when I changed command from `npx expo start --ios` to `npx expo run:ios` it stops crashing, yet still giving me this error in the console

**Comment by ravibhardwaj24** [comment]
Faced same issue in my react native expo project, markers images get flicker and in some devices that image getting cut from either of the side. I also upgrade the version to 1.24.2 from 1.20.1 which i suggested by npx expo install react-native-maps and also try 1.25.3 which is latest now but after upgrading the version to different version than 1.20.1 get this TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” error. My expo version is (expo: "~53.0.15") 

I’m facing the same issue in my Expo SDK 53 project (expo: "~53.0.15").

With react-native-maps@1.20.1, the app works but marker images flicker continuously and sometimes gets cut off on certain devices.

When upgrading to 1.24.2 (via npm i react-native-maps@1.24.2) or 1.25.3 (latest), the app crashes with:

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found.
Verify that a module by this name is registered in the native binary.
js engine: hermes


This issue occurs both in Expo Go and in development/production builds.

Environment:

Expo SDK: 53

React Native Maps: 1.20.1 (works but flickers), 1.24.2+ (crashes)

React Native: 0.79.4 (Expo SDK 53 default)

Platform: Android (tested), sometimes also affect iOS

Is there a recommended version of react-native-maps that:

Fixes the flickering / cut-off marker images issue?

**Comment by AlejandroRM-DEV** [comment]
> Faced same issue in my react native expo project, markers images get flicker and in some devices that image getting cut from either of the side. I also upgrade the version to 1.24.2 from 1.20.1 which i suggested by npx expo install react-native-maps and also try 1.25.3 which is latest now but after upgrading the version to different version than 1.20.1 get this TurboModuleRegistry.getEnforcing(…): ‘RNMapsAirModule’ Could Not Be Found” error. My expo version is (expo: "~53.0.15")
> 
> I’m facing the same issue in my Expo SDK 53 project (expo: "~53.0.15").
> 
> With react-native-maps@1.20.1, the app works but marker images flicker continuously and sometimes gets cut off on certain devices.
> 
> When upgrading to 1.24.2 (via npm i react-native-maps@1.24.2) or 1.25.3 (latest), the app crashes with:
> 
> Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMapsAirModule' could not be found. Verify that a module by this name is registered in the native binary. js engine: hermes
> 
> This issue occurs both in Expo Go and in development/production builds.
> 
> Environment:
> 
> Expo SDK: 53
> 
> React Native Maps: 1.20.1 (works but flickers), 1.24.2+ (crashes)
> 
> React Native: 0.79.4 (Expo SDK 53 default)
> 
> Platform: Android (tested), sometimes also affect iOS
> 
> Is there a recommended version of react-native-maps that:
> 
> Fixes the flickering / cut-off marker images issue?

Did you find a workaround? :(

**Comment by salah-ghanim** [comment]
Please use the latest version of the lib with the latest version of exp, those issues should be solved now.

if not please open a new ticket, but the stability has been significantly improving in latest releases.

**Comment by ksdagun** [comment]
Still not fixed when I update to latest version, and added the react-native-maps in plugins when you run expo prebuild --clean the google api key will not be added to android manifest, so the app will crash, API key not found.

But when I reverted back to 1.20.1 then run expo prebuild --clean the api key will now be added to android manifest

expo: 54
react-native-maps: latest

**Comment by Milwaukey** [comment]
Also having all these problems, tried upgrading, but it just crashes the app instead and doesn't solve the problem.
