### ISSUE TITLE
IOS: onUserLocationChange always gives accuracy, altitude, timestamp and others as zero

### ISSUE THREAD

**Issue by yesmanmx** [react-native-maps/react-native-maps#5721]
### Summary

onUserLocationChange always gives all fields except of latitude and longitude as zero

### Reproducible sample code

```TSX
import React, { useCallback } from 'react';
import MapView, { UserLocationChangeEvent } from 'react-native-maps';

const ExplorationMap = () => {

  const emitLocationChange = useCallback((locationUpdate: UserLocationChangeEvent) => {
    const nativeCoordinate = locationUpdate.nativeEvent.coordinate;

    console.log('native', nativeCoordinate);
  }, []);

  return (
    <MapView
      showsUserLocation={true}
      onUserLocationChange={emitLocationChange}
    />
  );
};

export default ExplorationMap;
```

### Steps to reproduce

1. Launch the app
2. See logs

Logs:
```
 LOG  native {"accuracy": 0, "altitude": 0, "altitudeAccuracy": 0, "heading": 0, "isFromMockProvider": false, "latitude": XXX, "longitude": XXX, "speed": 0, "timestamp": 0}
```

### Expected result

Values are provided for all fields of the `UserLocationChangeEvent` object

### Actual result

Values are provided only for all latitude and longitude field

### React Native Maps Version

1.26.1

### What platforms are you seeing the problem on?

iOS (Google Maps), iOS (Apple Maps)

### React Native Version

0.80.2

### What version of Expo are you using?

SDK 53

### Device(s)

iPhone 12 Pro, iPhone 13 Pro

**Comment by yesmanmx** [comment]
Worked as expected on version `1.20.1`

**Comment by wesbeard** [comment]
I'm also seeing this on iOS and haven't found a stable version to rollback to unfortunately, keeping my eyes peeled for a fix or workaround 👀

**Comment by KonstantinSavik** [comment]
The same for me!

**Comment by salah-ghanim** [comment]
fixed in [v1.26.6](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.26.6)

thanks for reporting

**Comment by wesbeard** [comment]
I'm still experiencing this on version 1.26.9 unfortunately :(

Coordinates are reported correctly but all over values are reported as zero

**Comment by KonstantinSavik** [comment]
Unfortenantly the same for me with 1.26.6 version

**Comment by yesmanmx** [comment]
@salah-ghanim , the issue is still reproducing

Also noticed one more issue: I am receiving an event for each minimal mobile move. Simple phone rotation in a hand produces a hundred events! Do you think I should create a separate issue for this?
